# SPDX-FileCopyrightText: Daniele Nicolodi <daniele@grinta.net>
# SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later

name: build
on:
  push:
    tags:
      - 'v[0-9]*'

permissions: {}

jobs:

  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: ubuntu-24.04-arm
          - os: windows-latest
            architecture: x86
          - os: windows-latest
            architecture: x64
          - os: windows-11-arm
            architecture: arm64
          - os: macos-15-intel
          - os: macos-14
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: bus1/cabuild/action/msdevshell@06ea2833eef61e9b0d0ce0d728416e617e4fb1fe  # v1
        with:
          architecture: ${{ matrix.architecture }}
        if: runner.os == 'Windows'
      - uses: actions/setup-python@v7
        with:
          python-version: '3.14'
      - run: echo "${{ case(matrix.architecture == 'x64', 'AMD64', matrix.architecture) }}"
      - run: pipx run --python 3.14 cibuildwheel==4.2.1
        env:
          CIBW_SKIP: '*-musllinux*'
          CIBW_ARCHS: ${{ case(matrix.architecture == 'x64', 'AMD64', matrix.architecture) }}
          CIBW_TEST_COMMAND: python {project}/test.py
      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.architecture }}
          path: wheelhouse/*.whl

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - run: python -m pip install build
      - run: python -m build --sdist
      - uses: actions/upload-artifact@v7
        with:
          name: sdist
          path: dist/*.tar.gz

  upload:
    needs:
      - wheels
      - sdist
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment: upload
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: dist
      - uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
